all:healthcenter patient doctor
.PHONY:all


healthcenter: healthcenter.cpp 
	g++ -o healthcenter healthcenter.cpp -lnsl -lresolv
patient: patient.cpp
	g++ -o patient patient.cpp -lnsl -lresolv
doctor: doctor.cpp
	g++ -o doctor doctor.cpp -lnsl -lresolv
